





#ifndef __LGSM_H__
#define __LGSM_H__




/* ID enum */ 
enum
{
  MDM_NO_STRING,  /* Unknown string */ 
 
  MDM_OK,         /* "OK" */ 
  MDM_BUSY,       /* "BUSY" */ 
  MDM_NO_ANSWER,  /* "NO ANSWER" */ 
  MDM_NO_CARRIER, /* "NO CARRIER" */ 
  MDM_CONNECT,    /* "CONNECT" */ 
  MDM_ERROR,      /* "ERROR" */ 
  MDM_CME_ERROR,  /* "+CME ERROR:" */ 
  MDM_CMS_ERROR,  /* "+CMS ERROR:" */ 
  MDM_CPIN,       /* "+CPIN:" */ 
  MDM_TIME_OUT,

  MDM_LAST_TERMINAL,      /* All terminal responses are before this line */ 

  MDM_RING = MDM_LAST_TERMINAL,   /* "RING" */ 
  MDM_CRING,      /* "+CRING:" */ 
  MDM_CPINC,      /* "+CPINC:" */ 
  MDM_CMEE,       /* "+CMEE:" */ 
  MDM_CREG,       /* "+CREG:" */ 
  MDM_CGREG,      /* "+CGREG:" */ 
  MDM_CRC,        /* "+CRC:" */ 
  MDM_CGEV,       /* "+CGEV:" */ 
  MDM_CGEREP,     /* "+CGEREP:" */ 

  MDM_IPR,
  MDM_COPS,
  MDM_CCLK,
  MDM_CFUN,
  MDM_CGSN,
  MDM_CGMR,
  MDM_CCID,
  MDM_CGMM,
  MDM_CGMI,
  MDM_CSQ,
  MDM_SIM,
  MDM_CMGR,
  MDM_CMGL,
  MDM_CNUM, 
  MDM_CIMI,
  MDM_CSCA,
  MDM_CMGW,
  MDM_CPAS,
  MDM_CPBR,
  MDM_CMUT,
  MDM_CLIP,
  MDM_CCWA,
  MDM_CMTI,
  MDM_CRSL,
  MDM_PIN,
  MDM_PUK,
  MDM_CGCLASS,
  MDM_CGACT,
  MDM_CGDCONT,
  MDM_CGATT,

  /* Last string ID */ 
  MDM_LAST
} ;




/* AT command ids */
typedef enum 
{

/* returns an alphanumeric string indicating the status 
of the SIM card, and whether a password is 
required or not. This is an independent 
SIM card lock status check only, and does 
not check the phone lock status. */
  PIN_QUERY=1,
  QUERY_SUBSCRIBER_NUMBERS,
  QUERY_SUBSCRIBER_NUMBERS_FROM_PHONEBOOK,
  REPLY_COMMAND,
  SOFT_RESET,
  ATT,
  DTR_SET,
  AUTO_ANSWER,
  COMMAND_ECHO,
  SET_OP_QUERY_REPLY,
  PIN_SETUP,
  PIN_CHANGE,
  PUK_SETUP,
  SET_PDU_MODE,
  SET_TXT_MODE,
  SET_OPERATOR,
  SET_OPERATOR_LOCKED,
  CUR_OP_QUERY,
  OPS_QUERY,
  POWER_ON,
  SOFTWARE_FOLW_CONTROL_ON,
  MODEM_STATUS_QUERY,
  NETWORK_REG_QUERY,
  NETWORK_REG_ENABLE,
  NETWORK_REGISTER,
  GPRS_NETWORK_REG_QUERY,
  SIGNAL_QUERY,
  ACTIVATE_CALL,
  QUERY_SEND_IDENTIFICATION,
  SET_SEND_IDENTIFICATION,
  CUR_CALLS_QUERY,
	CALL_RI_SET,
	CALL_RING,
  ACCEPT_CALL,
  HANGUP_CALLS,
  HANGUP_CURRENT,
  RELEASE_CALL,
  RELEASE_HELD,
  INITIATE_CALL,
  MUTE_QUERY,
  ENABLE_CLIP,
  ENABLE_CNMI,
  ENABLE_CMEE,
  ENABLE_CCWA,
  ENABLE_ECHO,
  READ_SERIAL_PORT_RATE,
  SET_SERIAL_PORT_RATE,
  SET_DATE_TIME,
  DATE_TIME_QUERY,
  SMS_READ,
  SMS_SEND,
  SMS_STORE,
  SIM_SEND,
  SIM_RING_INDICATOR,
  SMS_DELETE,
  SMS_DELETE_ALL,
  SMS_SET_CENTER,
  SMS_CENTER_QUERY,
  SMS_LIST,
  SMS_INIT,
  RING_VOLUME_QUERY,
  SEND_DTMF,
  ESCAPE_COMMAND,
  RETURN_TO_DATA_STATE,
  SERVICE_BEARER_QUERY,
  SET_SERVICE_BEARER,
  CAPABILITIES_GET,
  MANUFACTURER_QUERY,
  MODEL_QUERY,
  SW_REVISION_QUERY,
  SW_CCID_QUERY,
  IMEI_QUERY,
  IMSI_QUERY,
  ANTENNA_POWER_GET,
  ANTENNA_POWER_SET,
  PHONEBOOK_SIM_OWN_NUMBERS_SET,
  PHONEBOOK_ENTRY_ON_SET,
  PHONEBOOK_SPACE_SET,
  PHONEBOOK_SPACES_QUERY,
  PHONEBOOK_STATUS_QUERY,
  PHONEBOOK_GET_INDEX_BOUNDARIES,
  PHONEBOOK_ENTRY_GET,
  PHONEBOOK_ENTRY_SET,
  PHONEBOOK_ENTRY_DELETE,
  
  ATTACH_GPRS_NETWORK,
  DETACH_GPRS_NETWORK,
  GPRS_CONTEXT_ACT,
  GPRS_CONTEXT_NO_ACT,
  SOCKET_CONFIGURATION,
  SOCKET_CONFIGURATION_EXTERND,
  PPP_PARAM_CONFIG,
  SOCKET_DIAL,
  GPRS_SSEND,
  CFG_HTTP_PARAMS,
  CONTEXT_ACTIVATION,
  CONTEXT_ACT_CONFIG,
  DNS_CACH,
  REQUEST_LOCATION,
  FTP_OPEN,
  FTP_CLOSE,
  FTP_TIME_OUT,
  FTP_GET_FILESIZE,
  FTP_GET_FILE,
  SOCKET_SHUTDOWN,
  SOCKET_RESTORE,
  SOCKET_INACTIVE_TIMEOUT,
  SOCKET_SET,
  SOCKET_OPEN,
  SELECT_FLOW_CONTROL,
  STAT_LED_GPIO_SET,
  LIST_GPRS_CLASSES,
  SELECT_GPRS_CLASS,
  ACTIVE_PDP_CONTEXT,
  DEACTIVE_PDP_CONTEXT,
  SELECT_PDP_CONTEXT,
  ADD_PDP_CONTEXT,
	CTCC_ADD_PDP_CONTEXT,
  DELETE_PDP_CONTEXT,
  LIST_PDP_CONTEXT,
  REQUEST_GPRS_SERVICE,


  /* 厂商专属指令区 */
  //////////////////////////////////////////////////////

  /* MC37I专属指令区 */
  USING_SYNC_PIN,
  SWITCH_OFF_MS,
  SET_AUDIO_HARDWARE,
  GET_AUDIO_HARDWARE,
  SET_LOUDSPEAKER_VOLUME,
  GET_LOUDSPEAKER_VOLUME,

  //////////////////////////////////////////////////////

  VENDOR_COMMAND

} AtCommandID;



#endif  /* __LGSM_H__ */


